language: java
sudo: false

jdk:
  - oraclejdk8 

install:
  - gradle assemble

script:
  - gradle check
  - javadoc -private -sourcepath "src/main/java:src/test/java" -d doc/ fr.unistra.fizzbuzz

deploy:
  provider: pages
  local-dir: doc
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
